// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {Groth16Verifier} from "../src/verifiers/DepthPoCDVerifier.sol";

/// @notice D2 GATE — on-chain (EVM) verification of the DepthCurve PoCD proof.
///
/// Proof + public signals generated by `circuits/build_pocd_gate.sh` for a
/// homomorphic sum of Enc(100)+Enc(250) encrypted to the auditor key, claiming
/// Σ = 350. Public signals: [Csum_c1.x, Csum_c1.y, Csum_c2.x, Csum_c2.y,
/// claimedSum, auditorPub.x, auditorPub.y].
contract DepthPoCDGateTest is Test {
    Groth16Verifier internal verifier;

    uint256[2] A = [
        0x1ae46d57da6200ae1ecd510572470e5856341077b3b9923f04e56a73e1f4e15d,
        0x051a1a8a806b3b90f260acb59a0a21f9e0b403e584fa9f9a1b3748caa1e71748
    ];
    uint256[2][2] B = [
        [
            0x2021d8ea5717f57e2ce0b381e9a8a90e91202e443df0c98ccea3fedca8858513,
            0x196b718bae00121b929e3e0da1aa77db3dfc85b88f1c990a4174dca9c78b0688
        ],
        [
            0x1e189529963e0a13275d85ed4db16a9fac56b119d92e05894fca1c17561544f8,
            0x0bba01cecb5bc6d16d0fd1328cea13c822f05b4f941c41281741d10d3ca6e72d
        ]
    ];
    uint256[2] C = [
        0x078b4d84a64e493b3095151e9fee471a3e9e032cc6537271a5810db508d587e4,
        0x24728d2637b8fdfb6178d858db9520cd98bc9cb0fd2f6b74d98973056967ca9f
    ];
    uint256[7] PUB = [
        0x13fbc1886714d64e06026f85cbfec36e01455dfc8f39adc20dcfff8a4bc192e2,
        0x2af941ff287586957b33c7f2c8c06a67f85fd38ddf8e35a4cb2189435e25437f,
        0x2f5730f98d9df06b868dfadad0d8d696e7d12b49764922a3a2a2088bc72d2b3d,
        0x0cfce4c808a9ab12c6037466a9cb5ebbfa94e522cf8e9e334bebc32793cc9a18,
        0x000000000000000000000000000000000000000000000000000000000000015e, // 350
        0x217116360dc755d44ce49fc4e418f15812c48070be150ae380bf8481af1d6704,
        0x1097a10db5191b94d204f0ea36037602fdbe433f2a4c62d9244c24e59d9b6b8c
    ];

    function setUp() public {
        verifier = new Groth16Verifier();
    }

    /// @dev GATE PASS condition: a valid PoCD over an on-chain homomorphic sum
    ///      verifies in the EVM.
    function test_ValidProofVerifies() public view {
        assertTrue(verifier.verifyProof(A, B, C, PUB), "valid PoCD must verify");
    }

    /// @dev Soundness: tampering the claimed sum (350 -> 351) must fail.
    function test_TamperedClaimedSumFails() public view {
        uint256[7] memory bad = PUB;
        bad[4] = 351;
        assertFalse(verifier.verifyProof(A, B, C, bad), "tampered claim must not verify");
    }

    /// @dev Soundness: tampering a proof element must fail.
    function test_TamperedProofFails() public view {
        uint256[2] memory badA = A;
        badA[0] = A[0] ^ 1;
        assertFalse(verifier.verifyProof(badA, B, C, PUB), "tampered proof must not verify");
    }

    function test_MeasureVerifyGas() public {
        uint256 g0 = gasleft();
        bool ok = verifier.verifyProof(A, B, C, PUB);
        uint256 used = g0 - gasleft();
        emit log_named_uint("PoCD on-chain verify gas", used);
        assertTrue(ok);
    }
}
