// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {DepthPoCDArrayVerifier} from "../src/verifiers/DepthPoCDArrayVerifier.sol";
import {PoCDVerifierAdapter} from "../src/verifiers/PoCDVerifierAdapter.sol";

/// @notice Phase B — on-chain (EVM) verification of the 37-tick DepthCurve array PoCD,
///         through the dynamic PoCDVerifierAdapter seam (as MONIAOracle uses it).
///         Proof + 372 public signals loaded from test/fixtures/depth_array.json
///         (generated by packages/eerc-node/src/emit_array_fixture.mjs).
contract DepthPoCDArrayGateTest is Test {
    DepthPoCDArrayVerifier verifier;
    PoCDVerifierAdapter adapter;

    uint256[2] A;
    uint256[2][2] B;
    uint256[2] C;
    uint256[] PUB;

    function setUp() public {
        verifier = new DepthPoCDArrayVerifier();
        adapter = new PoCDVerifierAdapter(address(verifier));

        string memory j = vm.readFile("test/fixtures/depth_array.json");
        uint256[] memory a = vm.parseJsonUintArray(j, ".a");
        uint256[] memory b0 = vm.parseJsonUintArray(j, ".b0");
        uint256[] memory b1 = vm.parseJsonUintArray(j, ".b1");
        uint256[] memory c = vm.parseJsonUintArray(j, ".c");
        PUB = vm.parseJsonUintArray(j, ".pub");
        A = [a[0], a[1]];
        B = [[b0[0], b0[1]], [b1[0], b1[1]]];
        C = [c[0], c[1]];
    }

    function test_ArrayProofVerifiesThroughAdapter() public view {
        assertEq(PUB.length, 372, "372 public signals");
        assertTrue(adapter.verifyProof(A, B, C, PUB), "valid array PoCD must verify");
    }

    function test_TamperedSignalFails() public {
        uint256[] memory bad = PUB;
        bad[371] = bad[371] ^ 1; // last signal (a bidSum) tampered
        assertFalse(adapter.verifyProof(A, B, C, bad), "tampered signal must not verify");
    }

    function test_WrongLengthReverts() public {
        uint256[] memory short = new uint256[](371);
        vm.expectRevert(PoCDVerifierAdapter.BadInputLength.selector);
        adapter.verifyProof(A, B, C, short);
    }
}
